const data = {
  products: [
    {
      _id: "1",
      name: "h",
      category: "Shirts",
      image: "/images/p1.png",
      price: 120,
      brand: "Nike",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
        _id: "2",
        name: "a",
        category: "Shirts",
        image: "/images/p1.png",
        price: 33,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "high quality product",
      },
      {
        _id: "3",
        name: "Nicke Slim Shirt",
        category: "Shirts",
        image: "/images/p1.png",
        price: 66,
        brand: "Nike",
        rating: 2,
        numReviews: 10,
        description: "high quality product",
      },
      {
        _id: "4",
        name: "Nicke Slim Shirt",
        category: "Shirts",
        image: "/images/p1.png",
        price: 120,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "high quality product",
      },
      {
        _id: "5",
        name: "Nicke Slim Shirt",
        category: "Shirts",
        image: "/images/p1.png",
        price: 120,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "high quality product",
      },
      {
        _id: "6",
        name: "Nicke Slim Shirt",
        category: "Shirts",
        image: "/images/p1.png",
        price: 120,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "high quality product",
      },
  ],
};

export default data;
