const data = {
  store: [
    {
      _id: "1",
      name: "콜드브루",
      category: "coldbrew",
      image: "/images/coldbrew.jpg",
      price: "5,500",
      countInStock: 0,
      brand: "STARBUCKS",
      description: "high quality product",
      review: [
        {
          rating: 5,
          content: "최고의 맛입니다!",
        },
        {
          rating: 4,
          content: "진짜 맛있어요!",
        },
      ],
    },
    {
      _id: "2",
      name: "아이스 커피",
      category: "Coffee",
      image: "/images/icecoffee.jpg",
      price: "4,500",
      countInStock: 100,
      brand: "STARBUCKS",
      description: "high quality product",
      review: [
        {
          rating: 5,
          content: "최고의 맛입니다!",
        },
        {
          rating: 4,
          content: "진짜 맛있어요!",
        },
      ],
    },
    {
      _id: "3",
      name: "콜드브루 오트 라떼",
      category: "Coffee",
      image: "/images/coldbrewoat.jpg",
      price: "6,500",
      countInStock: 1,
      brand: "STARBUCKS",
      description: "high quality product",
      review: [
        {
          rating: 5,
          content: "최고의 맛입니다!",
        },
        {
          rating: 4,
          content: "진짜 맛있어요!",
        },
      ],
    },
    {
      _id: "4",
      name: "콜드브루",
      category: "coldbrew",
      image: "/images/coldbrew.jpg",
      price: "5,500",
      countInStock: 7,
      brand: "STARBUCKS",
      description: "high quality product",
    },
    {
      _id: "5",
      name: "아이스 커피",
      category: "Coffee",
      image: "/images/icecoffee.jpg",
      price: "4,500",
      countInStock: 5,
      brand: "STARBUCKS",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "콜드브루 오트 라떼",
      category: "Coffee",
      image: "/images/coldbrewoat.jpg",
      price: "6,500",
      countInStock: 3,
      brand: "STARBUCKS",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "콜드브루",
      category: "coldbrew",
      image: "/images/coldbrew.jpg",
      price: "5,500",
      brand: "STARBUCKS",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "아이스 커피",
      category: "Coffee",
      image: "/images/icecoffee.jpg",
      price: "4,500",
      countInStock: 2,
      brand: "STARBUCKS",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "9",
      name: "콜드브루 오트 라떼",
      category: "Coffee",
      image: "/images/coldbrewoat.jpg",
      price: "6,500",
      countInStock: 10,
      brand: "STARBUCKS",
      description: "high quality product",
    },
  ],
};

export default data;
